runtime: python
env: flex

runtime_config:
  python_version: 3.6

entrypoint: gunicorn -b :$PORT -b :5000 api:app

handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /create
  script: api.app
- url: /update
  script: api.app
- url: /delete
  script: api.app
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html

network:
  forwarded_ports:
    - 5000/tcp
